# Spring Boot daemon

This project demonstrates how a Spring Boot application can be managed as a service.

## Building

You need Java 1.8 and a bash-like shell. To build the project, invoke this command at
the root of the project

[source,bash]
----
$ ./mvnw clean install
----

## Unix

A `unix` distribution is generated automatically and uses `jsvc`. It is added for demonstration purpose only
as Spring Boot `1.3.x` has http://docs.spring.io/spring-boot/docs/1.3.0.M5/reference/htmlsingle/#deployment-service[better support for this]

## Windows

The `windows` distribution uses https://github.com/kohsuke/winsw[`winsw`].

WARNING: You need to install the `.NET` framework on the target machine first.

To install the sample application as a service, extract the distribution somewhere and open a shell with
administrative rights in that directory. Then invoke the following command

[source,bash]
----
$ spring-boot-daemon-sample.exe install
----

[NOTE]
====
`spring-boot-daemon-sample` is the identifier of the service. You can control that via Maven properties
in the `spring-boot-daemon-sample` project.
====

Once the service has been installed, you can start it the usual way, that is:

[source,bash]
----
$ net start spring-boot-daemon-sample
----

The logs are available in the `logs` directory of the distribution.

## License

Spring Boot Daemon is Open Source software released under the
http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].