# Spring Boot Daemon

This project enables a Spring Boot application to be managed as a service on Windows.

## Building

You need Maven to build the project and a simple `mvn package` at the root will do.

## Unix

There is no need for Spring Boot Daemon on Unix thanks to the native Spring Boot support from 1.3 onwards.

## Windows

The `windows` distribution uses https://github.com/kohsuke/winsw[`winsw`].

WARNING: You need to install the `.NET` framework on the target machine first.

## Sample applications

To install the sample application as a service, extract the distribution somewhere and open a shell with
administrative rights in that directory. Then invoke the following command

[source,bash]
----
$ spring-boot-daemon-sample.exe install
----

[NOTE]
====
`spring-boot-daemon-sample` is the identifier of the service. You can control that via Maven properties
in the `spring-boot-daemon-sample` project.
====

Once the service has been installed, you can start it the usual way, that is:

[source,bash]
----
$ net start spring-boot-daemon-sample
----

The logs are available in the `logs` directory of the distribution.

## Usage

To enable running your own Spring Boot applications as a Windows Service:

1. add `net.kemitix:spring-boot-daemon-integration` as a dependency
2. copy, unaltered, the assembly and dist directories from `spring-boot-daemon-sample/src/main` into your own application
sources
3. add the `build/plugins` section from `spring-boot-daemon-sample/pom.xml` to your own `pom.xml`
4. add the following properties to your `pom.xml`, updating the values to suit

[source,xml]
----
    <properties>
        <dist.dir>${project.build.directory}/dist</dist.dir>
        <dist.project.id>${project.artifactId}</dist.project.id>
        <dist.project.name>Sample Spring Boot App</dist.project.name>
        <dist.project.description>
            Demonstrate how to integrate a Spring Boot app as a Windows Service
        </dist.project.description>
        <dist.start.class>net.nicoll.SampleApplication</dist.start.class>
        <dist.jmx.port>50201</dist.jmx.port>
    </properties>
----
